### ISSUE TITLE
Add support to update/patch EVC

### ISSUE THREAD

**Issue by beraldoleal** [kytos/mef_eline#46]

**Comment by macartur** [comment]
This is already implemented in the method [Main.update](https://github.com/kytos/mef_eline/blob/master/main.py#L124)

**Comment by beraldoleal** [comment]
@ajoaoff told us that this is not working properly. We should do a double check.

**Comment by hdiogenes** [comment]
The error that happens now is this:

```
2018-12-14 12:02:06,731 - ERROR [flask.app] (Thread-231) Exception on /api/kytos/mef_eline/v2/evc/bd1845390151416885f71da9c4ad8d3e [PATCH]
Traceback (most recent call last):
  File "/Users/humberto/src/envs/ky/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/humberto/src/envs/ky/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/humberto/src/envs/ky/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/humberto/src/envs/ky/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/humberto/src/envs/ky/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/humberto/src/envs/ky/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/humberto/src/envs/ky/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/humberto/src/envs/ky/var/lib/kytos/napps/kytos/mef_eline/main.py", line 142, in update
    evc.update(**data)
  File "/Users/humberto/src/envs/ky/var/lib/kytos/napps/../napps/kytos/mef_eline/models.py", line 221, in update
    self.sync()
  File "/Users/humberto/src/envs/ky/var/lib/kytos/napps/../napps/kytos/mef_eline/models.py", line 202, in sync
    self._storehouse.save_evc(self)
  File "/Users/humberto/src/envs/ky/var/lib/kytos/napps/../napps/kytos/mef_eline/storehouse.py", line 78, in save_evc
    self.box.data[evc.id] = evc.as_dict()
  File "/Users/humberto/src/envs/ky/var/lib/kytos/napps/../napps/kytos/mef_eline/models.py", line 292, in as_dict
    self.circuit_scheduler]
  File "/Users/humberto/src/envs/ky/var/lib/kytos/napps/../napps/kytos/mef_eline/models.py", line 291, in <listcomp>
    request_dict['circuit_scheduler'] = [sched.as_dict() for sched in
AttributeError: 'dict' object has no attribute 'as_dict'
```
