### ISSUE TITLE
A set of Links is created, but Link is not hashable

### ISSUE THREAD

**Issue by ajoaoff** [kytos/mef_eline#84]
On an `EVC`, links are cached in a `set`, but the `Link` class is not hashable. See the traceback:

```Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "kytos-env/lib/python3.6/site-packages/kytos-2018.2b2-py3.6.egg/kytos/core/helpers.py", line 72, in threaded_handler
    handler(*args)
  File "kytos-env/var/lib/kytos/napps/kytos/mef_eline/main.py", line 192, in trigger_evc_reprovisioning
    evc = self.evc_from_dict(data)
  File "kytos-env/var/lib/kytos/napps/kytos/mef_eline/main.py", line 252, in evc_from_dict
    return EVC(self.controller, **data)
  File "kytos-env/lib/python3.6/site-packages/napps/kytos/mef_eline/models.py", line 169, in __init__
    self.current_path = Path(kwargs.get('current_path', []))
  File "kytos-env/lib/python3.6/site-packages/napps/kytos/mef_eline/models.py", line 22, in __init__
    self.links_cache = set(self)
TypeError: unhashable type: 'Link'
```

**Comment by hdiogenes** [comment]
We can just use its uuid as the hash key:

```
   def __hash__(self):
        return hash(self._uuid)
```
